# Generated by Django 2.1.13 on 2019-10-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_sitepreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
