# Generated by Django 2.1.13 on 2019-10-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_sitepreferences_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='enable_fts',
            field=models.BooleanField(default=False),
        ),
    ]
