# Generated by Django 2.1.13 on 2019-10-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_sitepreferences_disable_forgot_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='disable_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
