# Generated by Django 2.1.13 on 2019-10-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_sitepreferences_enable_fts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='show_category_on_problems_page',
            field=models.BooleanField(default=False),
        ),
    ]
