# Generated by Django 2.2.6 on 2019-10-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_sitepreferences_disable_mail_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationrequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationrequest',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('see_private_problem', 'See hidden problems'), ('edit_own_problem', 'Edit own problems'), ('edit_all_problem', 'Edit all problems'), ('edit_public_problem', 'Edit all public problems'), ('clone_problem', 'Clone problem'), ('change_public_visibility', 'Change is_public field'), ('change_manually_managed', 'Change is_manually_managed field')), 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
        migrations.RemoveField(
            model_name='contest',
            name='is_organization_private',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='is_organization_private',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='sitepreferences',
            name='disable_organizations',
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='it determines whether the contest is visible', verbose_name='publicly visible'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationRequest',
        ),
    ]
