# Generated by Django 2.1.13 on 2019-10-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_sitepreferences_disable_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='members', related_query_name='member', to='judge.Organization', verbose_name='organization'),
        ),
    ]
