# Generated by Django 2.2.6 on 2019-11-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20191028_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='hide_submission_feedback',
        ),
        migrations.AddField(
            model_name='contest',
            name='show_submission_feedback',
            field=models.BooleanField(default=False, help_text='Hide submission feedback on submssion page.', verbose_name='hide submission feedback'),
        ),
    ]
