# Generated by Django 2.1.13 on 2019-10-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_sitepreferences_show_category_on_problems_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='enable_problem_search_on_problems_page',
            field=models.BooleanField(default=False),
        ),
    ]
