# Generated by Django 2.1.13 on 2019-10-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_sitepreferences_enable_problem_search_on_problems_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitepreferences',
            old_name='enable_problem_search_on_problems_page',
            new_name='simple_problems_page',
        ),
        migrations.RemoveField(
            model_name='sitepreferences',
            name='show_category_on_problems_page',
        ),
    ]
