# Generated by Django 2.1.13 on 2019-10-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20191018_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ace_theme',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_script',
        ),
    ]
