# Generated by Django 2.2.7 on 2019-11-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20191106_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='one_language_one_problem_mode',
            field=models.BooleanField(default=False, help_text='Mode for if a problem solved using a language, that language cannot be used again.', verbose_name='One language one problem mode'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='show_submission_feedback',
            field=models.BooleanField(default=False, help_text='Show submission feedback on submssion page.', verbose_name='show submission feedback'),
        ),
    ]
