# Generated by Django 2.1.13 on 2019-10-19 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_auto_20191018_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitepreferences',
            old_name='disable_password_change',
            new_name='disable_change_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='math_engine',
        ),
    ]
