# Generated by Django 2.1.13 on 2019-10-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_auto_20191014_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitepreferences',
            old_name='simple_problems_page',
            new_name='extended_problems_page',
        ),
    ]
