# Generated by Django 2.2.7 on 2019-11-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_auto_20191112_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='display name'),
        ),
    ]
