# Generated by Django 2.1.13 on 2019-10-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_auto_20191014_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='comments',
            field=models.BooleanField(default=False, help_text='Enable comments on contest page', verbose_name='enable comments'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='use_clarifications',
            field=models.BooleanField(default=True, help_text='Use clarification system instead of comments.', verbose_name='use clarification'),
        ),
    ]
