# Generated by Django 2.2.7 on 2019-11-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('judge', '0008_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='primary_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Primary user group to show on scoreboard'),
        ),
    ]
