# Generated by Django 2.1.13 on 2019-10-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_auto_20191014_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='comments',
        ),
        migrations.AddField(
            model_name='contest',
            name='no_comments',
            field=models.BooleanField(default=True, help_text='Disable comments on contest page', verbose_name='disable comments'),
        ),
    ]
