# Generated by Django 2.2.7 on 2019-12-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_auto_20191207_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='display name'),
        ),
    ]
