# Generated by Django 2.2.7 on 2019-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_auto_20191207_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='use_display_name_as_public_name',
            field=models.BooleanField(default=False),
        ),
    ]
