# Generated by Django 2.1.13 on 2019-10-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_auto_20191014_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='disable_social_share',
            new_name='no_social_share',
        ),
    ]
