# Generated by Django 2.2.11 on 2020-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_sitepreferences_use_display_name_as_public_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiscConfig',
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='extra_body_end_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='extra_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='extra_js',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problemtranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish')], max_length=7, verbose_name='language'),
        ),
    ]
