# Generated by Django 2.1.13 on 2019-10-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_auto_20191014_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='letter',
            field=models.CharField(default='a', max_length=3),
            preserve_default=False,
        ),
    ]
