# Generated by Django 2.1.13 on 2019-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0013_contestproblem_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='hide_points_on_scoreboard',
            field=models.BooleanField(default=False, help_text='Hide points on scoreboard page', verbose_name='hide points on scoreboard'),
        ),
    ]
