# Generated by Django 2.1.13 on 2019-10-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0015_auto_20191014_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group of problem, shown under Category in the problem list.', null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.ProblemGroup', verbose_name='problem group'),
        ),
    ]
