# Generated by Django 2.1.13 on 2019-10-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0016_auto_20191014_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='no_problem_comments',
            field=models.BooleanField(default=False),
        ),
    ]
