# Generated by Django 2.1.13 on 2019-10-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0017_sitepreferences_no_problem_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitepreferences',
            old_name='extended_problems_page',
            new_name='extended_filters',
        ),
        migrations.AlterField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[('atcoder', 'AtCoder'), ('cclub', 'CClub'), ('default', 'Default'), ('ecoo', 'ECOO'), ('ioi', 'IOI')], default='default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='letter',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
