# Generated by Django 2.1.13 on 2019-10-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0018_auto_20191014_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitepreferences',
            old_name='extended_filters',
            new_name='enable_filters',
        ),
    ]
