# Generated by Django 2.1.13 on 2019-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0019_auto_20191014_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='hide_best_solutions',
            field=models.BooleanField(default=False),
        ),
    ]
