# Generated by Django 2.1.13 on 2019-10-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0020_sitepreferences_hide_best_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='types',
            field=models.ManyToManyField(blank=True, help_text="The type of problem, as shown on the problem's page.", to='judge.ProblemType', verbose_name='problem types'),
        ),
    ]
