# Generated by Django 2.1.13 on 2019-10-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0021_auto_20191014_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='hide_participation_tab',
            field=models.BooleanField(default=False, help_text='Hide participation tab on contest page', verbose_name='hide participation tab'),
        ),
    ]
