# Generated by Django 2.1.13 on 2019-10-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0022_contest_hide_participation_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='active_contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.Contest'),
        ),
    ]
