# Generated by Django 2.1.13 on 2019-10-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0024_auto_20191014_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitepreferences',
            old_name='no_problem_comments',
            new_name='no_comments',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='no_comments',
        ),
    ]
