# Generated by Django 2.1.13 on 2019-10-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0025_auto_20191014_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='hide_points_on_scoreboard',
            new_name='hide_points',
        ),
    ]
