# Generated by Django 2.1.13 on 2019-10-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0026_auto_20191014_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='hide_problem_types',
            field=models.BooleanField(default=False, help_text='Whether problem types should be hidden by default.', verbose_name='hide problem types'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='hide_points',
            field=models.BooleanField(default=False, help_text='Hide points on all pages', verbose_name='hide points'),
        ),
    ]
