# Generated by Django 2.1.13 on 2019-10-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0027_auto_20191014_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='hide_problem_types',
        ),
    ]
