# Generated by Django 2.1.13 on 2019-10-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0028_remove_contest_hide_problem_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='enable_rss',
            field=models.BooleanField(default=False),
        ),
    ]
