# Generated by Django 2.1.13 on 2019-10-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0029_sitepreferences_enable_rss'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='freeze_scoreboard_after',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
