# Generated by Django 2.1.13 on 2019-10-14 20:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0030_contest_freeze_scoreboard_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='frozen_cumtime',
            field=models.PositiveIntegerField(default=0, verbose_name='frozen cumulative time'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='frozen_format_data',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='contest format specific data'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='frozen_score',
            field=models.IntegerField(db_index=True, default=0, verbose_name='frozen score'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[('cclub', 'CClub'), ('default', 'Default')], default='default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='freeze_scoreboard_after',
            field=models.DateTimeField(blank=True, help_text='Freeze scoreboard after this time.', null=True, verbose_name='freeze scoreboard after'),
        ),
    ]
